import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Sidebar from '@/components/themplate/Sidebar'
import Header from '@/components/themplate/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex h-screen overflow-hidden">

       
      


   
        {children}

      
        </body>
    </html>
  )
}
